name: Bump Version and Tag

on:
  push:
    branches:
      - main
      - features
      - release/*
      - bugfix
      
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1.0.0
      - uses: actions/setup-setup-dotnet@v1
      - uses: actions/setup-gitversion@v1.0.0
        with:
          gitversion-version: 5.1.1
      - run: GitVersion
